### PR TITLE
because we are not animals

### PR DESCRIPTION
**Pull request by acampb311**

### CODE REVIEW

**Comment by ShepherdJerred** [comment]
Why would I want my 6 line program to be 7 lines?

**Comment by acampb311** [comment]
It's simply the right thing to do:

> The K&R style is commonly used in C, C++, and other curly brace programming languages. Used in Kernighan and Ritchie's book The C Programming Language, it had its origins in Kernighan and Plauger's The Elements of Programming Style and Software Tools. When following K&R, each function has its opening brace at the next line on the same indent level as its header, the statements within the braces are indented, and the closing brace at the end is on the same indent level as the header of the function at a line of its own.

**Comment by ShepherdJerred** [comment]
Spaces vs Tabs

**Comment by acampb311** [comment]
This is why we can't have nice things.

**Pull request closed without merging**
